export const PREVIEW_IMAGES: Record<string, any> = {
  "Homescreen.png": require("@/assets/images/component_previews/Homescreen.png"),
  "Version=Default.png": require("@/assets/images/component_previews/Version=Default.png"),
  "Goals screen.png": require("@/assets/images/component_previews/Goals screen.png"),
  "Goals Details.png": require("@/assets/images/component_previews/Goals Details.png"),
  "AnalyticOverview.png": require("@/assets/images/component_previews/AnalyticOverview.png"),
  "Analytic Breakdown screen.png": require("@/assets/images/component_previews/Analytic Breakdown screen.png"),
  "Transaction History.png": require("@/assets/images/component_previews/Transaction History.png"),
  "Add transaction.png": require("@/assets/images/component_previews/Add transaction.png"),
  "Buttons.png": require("@/assets/images/component_previews/Buttons.png"),
  "Card.png": require("@/assets/images/component_previews/Card.png"),
  "chip.png": require("@/assets/images/component_previews/chip.png"),
  "Media Slot.png": require("@/assets/images/component_previews/Media Slot.png"),
  "Text Divider.png": require("@/assets/images/component_previews/Text Divider.png"),
  "Section title.png": require("@/assets/images/component_previews/Section title.png"),
  "Tag.jpg": require("@/assets/images/component_previews/Tag.jpg"),
  "Amount input.jpg": require("@/assets/images/component_previews/Amount input.jpg"),
  "Transaction Text Input.jpg": require("@/assets/images/component_previews/Transaction Text Input.jpg"),
  "Search Field.jpg": require("@/assets/images/component_previews/Search Field.jpg"),
  "List Item.png": require("@/assets/images/component_previews/List Item.png"),
  "Card Menu Item.png": require("@/assets/images/component_previews/Card Menu Item.png"),
  "Filter Chip.jpg": require("@/assets/images/component_previews/Filter Chip.jpg"),
  "Tab Item.jpg": require("@/assets/images/component_previews/Tab Item.jpg"),
  "Tab Bar.jpg": require("@/assets/images/component_previews/Tab Bar.jpg"),
  "BottomNavBar.png": require("@/assets/images/component_previews/BottomNavBar.png"),
  "NavigationBar.jpg": require("@/assets/images/component_previews/NavigationBar.jpg"),
  "HomeIndicatorBar.png": require("@/assets/images/component_previews/HomeIndicatorBar.png"),
  "BalanceCard.png": require("@/assets/images/component_previews/BalanceCard.png"),
  "ActivityItem.png": require("@/assets/images/component_previews/ActivityItem.png"),
  "BillingItem.png": require("@/assets/images/component_previews/BillingItem.png"),
  "Recap Card New.png": require("@/assets/images/component_previews/Recap Card New.png"),
  "Income Outcome Trend Card.png": require("@/assets/images/component_previews/Income Outcome Trend Card.png"),
  "Income Expense Card.jpg": require("@/assets/images/component_previews/Income Expense Card.jpg"),
  "Tooltip.jpg": require("@/assets/images/component_previews/Tooltip.jpg"),
  "Card Type Icon.png": require("@/assets/images/component_previews/Card Type Icon.png"),
  "Payment method icon.png": require("@/assets/images/component_previews/Payment method icon.png"),
  "Version=Minimize.png": require("@/assets/images/component_previews/Version=Minimize.png"),
  "Version=Detailed.png": require("@/assets/images/component_previews/Version=Detailed.png"),
  "ProgressBarWithController.png": require("@/assets/images/component_previews/ProgressBarWithController.png"),
  "Category Icon.png": require("@/assets/images/component_previews/Category Icon.png"),
  "Category Breakdown Item.jpg": require("@/assets/images/component_previews/Category Breakdown Item.jpg"),
  "Expense Chart.jpg": require("@/assets/images/component_previews/Expense Chart.jpg"),
  "SpendingChart.jpg": require("@/assets/images/component_previews/SpendingChart.jpg"),
  "IncomeExpenseChart.jpg": require("@/assets/images/component_previews/IncomeExpenseChart.jpg"),
  "Image Form.png": require("@/assets/images/component_previews/Image Form.png"),
  "Profile and Settings.png": require("@/assets/images/component_previews/Profile and Settings.png"),
}
