/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./.storybook/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        text: {
          primary: "var(--color-text-primary)",
          "primary-on-brand": "var(--color-text-primary-on-brand)",
          secondary: "var(--color-text-secondary)",
          "secondary-hover": "var(--color-text-secondary-hover)",
          "secondary-on-brand": "var(--color-text-secondary-on-brand)",
          tertiary: "var(--color-text-tertiary)",
          "tertiary-hover": "var(--color-text-tertiary-hover)",
          "tertiary-on-brand": "var(--color-text-tertiary-on-brand)",
          quaternary: "var(--color-text-quaternary)",
          "quaternary-on-brand": "var(--color-text-quaternary-on-brand)",
          white: "var(--color-text-white)",
          disabled: "var(--color-text-disabled)",
          placeholder: "var(--color-text-placeholder)",
          "placeholder-subtle": "var(--color-text-placeholder-subtle)",
          "brand-primary": "var(--color-text-brand-primary)",
          "brand-secondary": "var(--color-text-brand-secondary)",
          "brand-tertiary": "var(--color-text-brand-tertiary)",
          "brand-tertiary-alt": "var(--color-text-brand-tertiary-alt)",
          "error-primary": "var(--color-text-error-primary)",
          "error-primary-hover": "var(--color-text-error-primary-hover)",
          "warning-primary": "var(--color-text-warning-primary)",
          "success-primary": "var(--color-text-success-primary)",
        },
        border: {
          primary: "var(--color-border-primary)",
          secondary: "var(--color-border-secondary)",
          tertiary: "var(--color-border-tertiary)",
          disabled: "var(--color-border-disabled)",
          "disabled-subtle": "var(--color-border-disabled-subtle)",
          brand: "var(--color-border-brand)",
          "brand-alt": "var(--color-border-brand-alt)",
          error: "var(--color-border-error)",
          "error-subtle": "var(--color-border-error-subtle)",
        },
        fg: {
          primary: "var(--color-fg-primary)",
          secondary: "var(--color-fg-secondary)",
          "secondary-hover": "var(--color-fg-secondary-hover)",
          tertiary: "var(--color-fg-tertiary)",
          "tertiary-hover": "var(--color-fg-tertiary-hover)",
          quaternary: "var(--color-fg-quaternary)",
          "quaternary-hover": "var(--color-fg-quaternary-hover)",
          white: "var(--color-fg-white)",
          disabled: "var(--color-fg-disabled)",
          "disabled-subtle": "var(--color-fg-disabled-subtle)",
          "brand-primary": "var(--color-fg-brand-primary)",
          "brand-secondary": "var(--color-fg-brand-secondary)",
          "brand-secondary-subtle": "var(--color-fg-brand-secondary-subtle)",
          "error-primary": "var(--color-fg-error-primary)",
          "error-secondary": "var(--color-fg-error-secondary)",
          "warning-primary": "var(--color-fg-warning-primary)",
          "warning-secondary": "var(--color-fg-warning-secondary)",
          "success-primary": "var(--color-fg-success-primary)",
          "success-secondary": "var(--color-fg-success-secondary)",
        },
        bg: {
          primary: "var(--color-bg-primary)",
          "primary-hover": "var(--color-bg-primary-hover)",
          "primary-solid": "var(--color-bg-primary-solid)",
          secondary: "var(--color-bg-secondary)",
          "secondary-hover": "var(--color-bg-secondary-hover)",
          "secondary-subtle": "var(--color-bg-secondary-subtle)",
          "secondary-solid": "var(--color-bg-secondary-solid)",
          tertiary: "var(--color-bg-tertiary)",
          quaternary: "var(--color-bg-quaternary)",
          active: "var(--color-bg-active)",
          disabled: "var(--color-bg-disabled)",
          "disabled-subtle": "var(--color-bg-disabled-subtle)",
          overlay: "var(--color-bg-overlay)",
          "brand-primary": "var(--color-bg-brand-primary)",
          "brand-secondary": "var(--color-bg-brand-secondary)",
          "brand-solid": "var(--color-bg-brand-solid)",
          "brand-solid-hover": "var(--color-bg-brand-solid-hover)",
          "brand-section": "var(--color-bg-brand-section)",
          "brand-section-subtle": "var(--color-bg-brand-section-subtle)",
          "error-primary": "var(--color-bg-error-primary)",
          "error-secondary": "var(--color-bg-error-secondary)",
          "error-solid": "var(--color-bg-error-solid)",
          "error-solid-hover": "var(--color-bg-error-solid-hover)",
          "warning-primary": "var(--color-bg-warning-primary)",
          "warning-secondary": "var(--color-bg-warning-secondary)",
          "warning-solid": "var(--color-bg-warning-solid)",
          "success-primary": "var(--color-bg-success-primary)",
          "success-secondary": "var(--color-bg-success-secondary)",
          "success-solid": "var(--color-bg-success-solid)",
        },
        focus: {
          ring: "var(--color-focus-ring)",
          "ring-error": "var(--color-focus-ring-error)",
        },
      },
      fontFamily: {
        display: ["Literata", "Georgia", "serif"],
        body: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        number: ["Iceland", "system-ui", "sans-serif"],
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        /* Semantic scale — rem values based on 16px root (Figma design tokens) */
        tiny: ["0.6875rem", { lineHeight: "1rem" }],
        caption: ["0.8125rem", { lineHeight: "1rem" }],
        "body-small": ["0.9375rem", { lineHeight: "1.25rem" }],
        body: ["1.0625rem", { lineHeight: "1.5rem" }],
        h3: ["1.1875rem", { lineHeight: "1.5rem" }],
        h2: ["1.3125rem", { lineHeight: "1.75rem" }],
        h1: ["1.5rem", { lineHeight: "2rem" }],
        display: ["2.125rem", { lineHeight: "2.75rem" }],
        "display-xl": ["4.5rem", { lineHeight: "5rem" }],
        /* Standard aliases for general use */
        xs: ["0.8125rem", { lineHeight: "1rem" }],
        sm: ["0.9375rem", { lineHeight: "1.25rem" }],
        base: ["1.0625rem", { lineHeight: "1.5rem" }],
        lg: ["1.1875rem", { lineHeight: "1.5rem" }],
        xl: ["1.3125rem", { lineHeight: "1.75rem" }],
        "2xl": ["1.5rem", { lineHeight: "2rem" }],
        "3xl": ["2.125rem", { lineHeight: "2.75rem" }],
      },
      letterSpacing: {
        tighter: "-0.02em",
      },
      borderRadius: {
        "4xl": "2rem",
      },
    },
  },
  plugins: [],
}
