import { Platform, useWindowDimensions, View } from "react-native"

import { Typography } from "@/components/ui-kit/Typography"

function CrossPlatformIcon() {
  return (
    <View style={{ width: 24, height: 24, position: "relative" }}>
      <View
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          width: 16,
          height: 16,
          borderRadius: 4,
          borderWidth: 2,
          borderColor: "#6895f8",
          backgroundColor: "transparent",
        }}
      />
      <View
        style={{
          position: "absolute",
          bottom: 0,
          right: 0,
          width: 16,
          height: 16,
          borderRadius: 4,
          borderWidth: 2,
          borderColor: "#2f61f3",
          backgroundColor: "rgba(47, 97, 243, 0.2)",
        }}
      />
    </View>
  )
}

function TypeScriptIcon() {
  return (
    <Typography
      size="body"
      weight="bold"
      style={{ color: "#6895f8", fontSize: 16, letterSpacing: -1 }}
    >
      {"</>"}
    </Typography>
  )
}

function ProductionIcon() {
  return (
    <View style={{ width: 22, height: 24, alignItems: "center" }}>
      <View
        style={{
          width: 20,
          height: 20,
          borderRadius: 10,
          borderWidth: 2,
          borderColor: "#10b981",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <View
          style={{
            width: 8,
            height: 5,
            borderBottomWidth: 2,
            borderLeftWidth: 2,
            borderColor: "#10b981",
            transform: [{ rotate: "-45deg" }],
            marginTop: -2,
          }}
        />
      </View>
    </View>
  )
}

function NativeWindIcon() {
  return (
    <View style={{ width: 24, height: 18, justifyContent: "center", gap: 3 }}>
      {[16, 20, 14].map((w, i) => (
        <View
          key={i}
          style={{
            width: w,
            height: 2,
            borderRadius: 1,
            backgroundColor: i === 1 ? "#8b5cf6" : "rgba(139, 92, 246, 0.5)",
          }}
        />
      ))}
    </View>
  )
}

interface FeatureCardProps {
  icon: React.ReactNode
  title: string
  description: string
  accentColor: string
  accentBg: string
}

function FeatureCard({ icon, title, description, accentColor, accentBg }: FeatureCardProps) {
  return (
    <View
      style={{
        flex: 1,
        minWidth: Platform.OS === "web" ? 260 : "100%",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "rgba(64, 73, 104, 0.3)",
        padding: 24,
        position: "relative",
        overflow: "hidden",
        backgroundColor: "rgba(17, 19, 34, 0.6)",
        ...(Platform.OS === "web" && {
          transition: "all 0.25s ease",
        }),
      }}
    >
      {/* Subtle accent gradient in top-right corner */}
      {Platform.OS === "web" && (
        <View
          style={{
            position: "absolute",
            top: -40,
            right: -40,
            width: 120,
            height: 120,
            borderRadius: 60,
            opacity: 0.08,
            backgroundColor: accentColor,
            ...(Platform.OS === "web" && {
              filter: "blur(40px)",
            }),
          }}
        />
      )}

      <View
        style={{
          width: 44,
          height: 44,
          borderRadius: 12,
          backgroundColor: accentBg,
          borderWidth: 1,
          borderColor: `${accentColor}30`,
          alignItems: "center",
          justifyContent: "center",
          marginBottom: 20,
        }}
      >
        {icon}
      </View>

      <Typography
        size="h3"
        weight="semibold"
        style={{ color: "#f9f9fb", marginBottom: 8 }}
      >
        {title}
      </Typography>

      <Typography
        size="body-small"
        style={{ color: "#7d89b0", lineHeight: 22 }}
      >
        {description}
      </Typography>
    </View>
  )
}

const FEATURES: (Omit<FeatureCardProps, "icon"> & { iconKey: string })[] = [
  {
    iconKey: "figma-to-code",
    title: "Figma to Code",
    description:
      "Every component is generated from production Figma designs using AI. Pixel-perfect translation from design to real code.",
    accentColor: "#ec4899",
    accentBg: "rgba(236, 72, 153, 0.12)",
  },
  {
    iconKey: "vibecoding",
    title: "100% Vibe Coded",
    description:
      "All components and screens generated by Cursor AI from Figma. 99% pixel-perfect fidelity with minimal human tweaks.",
    accentColor: "#8b5cf6",
    accentBg: "rgba(139, 92, 246, 0.12)",
  },
  {
    iconKey: "production",
    title: "Production Quality",
    description:
      "Not toy examples. Real, production-grade components with TypeScript, accessibility, and React Native Web support.",
    accentColor: "#10b981",
    accentBg: "rgba(16, 185, 129, 0.12)",
  },
  {
    iconKey: "ai-pipeline",
    title: "AI-Generated Pipeline",
    description:
      "Demonstrates the future of UI development: Design in Figma → Generate with AI → Ship to production.",
    accentColor: "#2f61f3",
    accentBg: "rgba(47, 97, 243, 0.12)",
  },
]

function FigmaToCodeIcon() {
  return (
    <View style={{ width: 24, height: 24, alignItems: "center", justifyContent: "center" }}>
      <View
        style={{
          width: 14,
          height: 14,
          borderRadius: 7,
          borderWidth: 2,
          borderColor: "#ec4899",
          marginBottom: -6,
        }}
      />
      <View
        style={{
          width: 16,
          height: 2,
          backgroundColor: "#ec4899",
          transform: [{ rotate: "-45deg" }],
        }}
      />
      <View
        style={{
          width: 12,
          height: 12,
          borderRadius: 2,
          borderWidth: 2,
          borderColor: "#10b981",
          marginTop: -4,
        }}
      />
    </View>
  )
}

function VibeCodingIcon() {
  return (
    <View style={{ width: 24, height: 24, alignItems: "center", justifyContent: "center" }}>
      <View style={{ flexDirection: "row", gap: 2 }}>
        <View style={{ width: 3, height: 12, backgroundColor: "#8b5cf6", borderRadius: 1 }} />
        <View style={{ width: 3, height: 18, backgroundColor: "#8b5cf6", borderRadius: 1 }} />
        <View style={{ width: 3, height: 14, backgroundColor: "#8b5cf6", borderRadius: 1 }} />
        <View style={{ width: 3, height: 10, backgroundColor: "#8b5cf6", borderRadius: 1 }} />
      </View>
    </View>
  )
}

function AIPipelineIcon() {
  return (
    <View style={{ width: 24, height: 24, alignItems: "center", justifyContent: "center" }}>
      <View
        style={{
          width: 20,
          height: 12,
          borderWidth: 2,
          borderColor: "#2f61f3",
          borderRadius: 4,
          alignItems: "center",
          justifyContent: "center",
        }}>
        <Typography size="caption" weight="bold" style={{ color: "#2f61f3", fontSize: 8 }}>
          AI
        </Typography>
      </View>
      <View
        style={{
          position: "absolute",
          bottom: 2,
          right: 2,
          width: 8,
          height: 8,
          borderWidth: 2,
          borderColor: "#10b981",
          borderLeftWidth: 0,
          borderTopWidth: 0,
        }}
      />
    </View>
  )
}

const ICON_MAP: Record<string, React.ReactNode> = {
  "figma-to-code": <FigmaToCodeIcon />,
  vibecoding: <VibeCodingIcon />,
  production: <ProductionIcon />,
  "ai-pipeline": <AIPipelineIcon />,
}

export function FeaturesSection() {
  const { width } = useWindowDimensions()
  const isDesktop = Platform.OS === "web" && width > 768

  return (
    <View style={{ width: "100%", paddingVertical: isDesktop ? 80 : 56, paddingHorizontal: 24 }}>
      {/* Section label */}
      <View style={{ alignItems: "center", marginBottom: 48, gap: 16 }}>
        <View
          style={{
            paddingHorizontal: 14,
            paddingVertical: 5,
            borderRadius: 20,
            borderWidth: 1,
            borderColor: "rgba(47, 97, 243, 0.3)",
            backgroundColor: "rgba(47, 97, 243, 0.08)",
          }}
        >
          <Typography
            size="caption"
            weight="semibold"
            style={{ color: "#6895f8", fontSize: 12, letterSpacing: 0.5 }}
          >
            FEATURES
          </Typography>
        </View>

        <Typography
          size="h2"
          weight="bold"
          className="text-center"
          style={{ color: "#f9f9fb", fontSize: isDesktop ? 36 : 28 }}
        >
          Vibe Coding in Action
        </Typography>

        <Typography
          size="body"
          className="text-center"
          style={{ color: "#7d89b0", maxWidth: 480 }}
        >
          See what's possible when AI translates Figma designs into production-ready React Native code
        </Typography>
      </View>

      {/* 2×2 Bento grid on desktop, stacked on mobile */}
      <View
        style={{
          flexDirection: "row",
          flexWrap: "wrap",
          gap: 16,
          justifyContent: "center",
          maxWidth: 720,
          alignSelf: "center",
          width: "100%",
        }}
      >
        {FEATURES.map((feature) => (
          <FeatureCard
            key={feature.title}
            icon={ICON_MAP[feature.iconKey]}
            title={feature.title}
            description={feature.description}
            accentColor={feature.accentColor}
            accentBg={feature.accentBg}
          />
        ))}
      </View>
    </View>
  )
}
